export const AuditAction = {
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_REFRESH: 'AUTH_REFRESH',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_EMAIL_VERIFIED: 'AUTH_EMAIL_VERIFIED',
  AUTH_VERIFICATION_RESENT: 'AUTH_VERIFICATION_RESENT',
  AUTH_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_PASSWORD_RESET_COMPLETED: 'AUTH_PASSWORD_RESET_COMPLETED',
  RBAC_ROLE_CREATED: 'RBAC_ROLE_CREATED',
  RBAC_ROLE_PERMISSIONS_UPDATED: 'RBAC_ROLE_PERMISSIONS_UPDATED',
  RBAC_USER_ROLES_UPDATED: 'RBAC_USER_ROLES_UPDATED',
  USER_APPROVAL_UPDATED: 'USER_APPROVAL_UPDATED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_STATUS_UPDATED: 'CATEGORY_STATUS_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_STATUS_UPDATED: 'PRODUCT_STATUS_UPDATED',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
} as const;

export interface AuditContext {
  requestId?: string;
  ip?: string;
  userAgent?: string;
}

export interface CreateAuditLog extends AuditContext {
  actorId?: string;
  action: (typeof AuditAction)[keyof typeof AuditAction];
  resource: string;
  resourceId?: string;
  status: 'SUCCESS' | 'FAILURE';
  before?: object;
  after?: object;
}
